; FRC translation file

; Note for translators:
;
; * Please *only* translate the text after the equal sign symbol ('=') in each row.  
; * Please do *not* remove any symbols or placeholders (like  &, %s, %d, \n, etc.) 
;   in your translated text - they are required to be found in your translation too.   
; Thank you!      

[main]

gui_OK=OK
gui_Cancel=Zrušit
gui_Yes=Ano 
gui_No=Ne 
gui_YesToAll=Ano, pro všechny 
gui_NoToAll=Ne pro všechny 
gui_Ignore=Ignorovat 
gui_Close=Zavřít 
gui_Exit=Výjezd 
gui_Warning=Varování 
gui_Error=Chyba 
gui_Information=Informace 
gui_Confirmation=Potvrzení 
gui_Progress=Pokrok...
gui_pleasewait=Prosím, vyčkejte...
gui_help=Pomoc
build_DEMO=Vyhodnocení

action_about=O 
action_buynow=Kup teď 
action_upgrade=Dotřídy 
action_createimage=Vytvořit obrazového souboru
action_exit=Výjezd 
action_help=Pomoc
action_loadimage=Načíst soubor obrázku 
action_options=Možnosti 
action_raid=RAID Reconstructor
action_rescan=Znovu vyhledat 
action_save=Uložit 
action_opensavepath=Otevřenou cestu pro uložení 
action_wipe=Utírat 
action_savefolderreport=Uložit zprávu 
action_search=Hledání 
action_selectall=Vybrat vše 
action_licadmin=Správa licencí
action_licactivate=Aktivace licence
action_fuzzysearch=Fuzzy vyhledávání 
action_openlogfile=Otevřete soubor protokolu
action_dálkovýrecovery=Vzdálené obnovení 
action_certmgr=Správce certifikátů
action_osdiskadmin=Disk správy 
action_view=Zobrazit jako HEX/Text 
action_resize=Změna velikosti položky 
action_rename=Přejmenování položky 
action_dálkovýrecview=Vzdálené obnovení Viewer 
action_refreshdisktree=Obnovit seznamu disků 
action_viewdisk=Disk prohlížeč (Hex)
action_restoreimage=Obnovit obrázek zvoleného testu objemu 
action_diskdiag=Disk diagnóza
action_diskinfo=Informace o disku
action_continue=Pokračovat 
action_goback=Vrátit se 
action_emailrecovery=Email zotavení
action_properties=Vlastnosti 
action_Wipedisk=Otřete disk 
action_scanreport=Zobrazit zprávu kontroly
action_addToScanReport=Přidat k prohledávání zprávy
action_skipitem=Přeskočit složky (přepínač)

hint_help=Spusťte soubor s nápovědou.
hint_exit=Konec programu 
hint_dálkovýrecovery=Začátek vzdálené obnovení session
hint_about=Zobrazit informace o programu 
hint_loadimagefile=Vložte disk image 
hint_createimagefile=Vytvoření obrazu disku 
hint_reconstructraid=Rebuild rozbité RAID
hint_buynow=Nákup programu 
hint_options=Nastavit možnosti programu 
hint_save=Uložit vybrané položky 
hint_opensavepath=Zobrazit obnovené položky ve Vaší cesty uložení.
hint_savefolderreport=Uložit soubor zprávy
hint_search=Hledání souborů a složek 
hint_selectall=Výběr všech položek 
hint_refreshdisktree=Aktualizace seznamu disků 
hint_wipe=Otřete vybraných položekhint_renameitem=Přejmenování položky 
hint_saveopen=Uložit a otevřete položku 
hint_openitem=Otevřené položky 
hint_resizeitem=Změna velikosti položky 
hint_licenseadmin=Správa licencí
hint_exportefs=Export zašifrovaný soubor 
hint_importefs=Dovoz zašifrovaný soubor 
hint_certmgr=Spusťte správce certifikátů 
hint_osdiskadmin=Spuštění OS disk správy 
hint_parentfolder=Přejít na nadřazené složky 
hint_dálkovýrecview=Spuštění vzdáleného diváka 
hint_licenseactivate=Aktivovat licenci 
hint_fuzzysearch=Povolit fuzzy vyhledávání
hint_upgrade=Zkontrolovat aktualizace 
hint_openlogfile=Otevřete logsouboru 
hint_view=Otevřete soubor s vnitřní prohlížeč 
hint_emailrecovery=Otevře se e-mailové Viewer
hint_addtoscanreport=Přidá vybrané položky na zprávu skenování 
hint_skipitem=Přeskočit složky a všech jejích podsložek v soubory (přepínač)
menuitem_fuzzysearch=Povolit fuzzy vyhledávání 
menu_file=Soubor
menu_edit=Upravit 
menu_search=Hledání 
menu_extras=Extra
menu_expert=Odborník 
menu_debug=Ladit 
menu_help=Pomoc
menu_license=Licence

popupmenumain_open=Otevřeno
popupmenumain_saveas=Uložit jako...
popupmenumain_saveopenfp=Uložit a otevřete složka...
popupmenumain_view=Zobrazit jako HEX/Text
popupmenumain_rename=Přejmenovat 
popupmenumain_resize=Změna velikosti 
popupmenumain_wipe=Utírat 
popupmenumain_exportefs=Export EFS
popupmenumain_importefs=Import EFS
popupmenumain_parentfolder=Přejít na nadřazené složky 

efsexport_good=Zašifrovaný soubor (y) úspěšně exportována do $EFS souboru. Šifrovací klíč je součástí.\n Prosím, export i vaše NTFS certifikát správce certifikátů,\n Pokud chcete importovat $EFS soubor (y) na jiném počítači.
efsexport_fail=Export do $EFS soubor (y) se nezdařilo. kódchyby =%d.  
efsimport_good=$EFS soubor (y) dovážet. V případě, že importovaný soubor není platný, je nutné importovat platný NTFS certifikát v tomto počítači.\n Použijte certicate manager na zdroj PC exportovat původní NTFS osvědčení,. 
efsimport_fail=Import z $EFS soubor (y) se nezdařilo. kódchyby =%d. 

popupmenuprogress_nexterr=Přejít na další chybu vstupních 
popupmenuprogress_openlogpath=Otevřeno logsouboru cesta 
popupmenuprogress_maillog=Pošta logsouboru na %s
popupmenuprogress_copy=Kopírovat do schránky 
popupmenuprogress_scrollstopstart=Zastavit/Obnovit rolování 

progressfrm_btncancel=Zrušit 
progressfrm_btnpause=Pauza
progressfrm_btnresume=Pokračovat
progressfrm_checkboxlog=Zobrazit zprávy protokolu 
progressfrm_listboxloghint=Použijte šipky nebo stránky nahoru a dolů pro navigaci. Klikněte pravým tlačítkem myši pro kontextovou nabídku.
progressfrm_estimatedtime=Odhadovaný zbývající čas: %s
progressfrm_seconds=%.0f sekundy 
progressfrm_minutes=%.1f minut 
progressfrm_hours=%.1f hodin
progressfrm_days=%.1f dnů 
progressfrm_foundfilesfolders=Nalezených souborů: %d, složky: %d
progressfrm_foundvolumesdisks=Nalezené množství: %d, disky: %d

wiz_welcome_top1=%s
wiz_welcome_top2=Obnova dat produktu %s
wiz_welcome_descr1=%s je snadno použitelný nástroj, který vám pomůže obnovit ztracené nebo smazané data a formátování a zkorumpované svazků. Obnovená data jsou uložena na jiný svazek, takže původní objem beze změny.
;wiz_welcome_descr2=
wiz_welcome_bottom=Další informace lze nalézt na adrese:
wiz_welcome_clickcontinue=Klikněte na "Pokračovat" pro spuštění obnovení průvodce, který vás provede procesem obnovy dat.  
wiz_stepx=Krok %d
wiz_details=(Klikněte pro detail) 
wiz_media=Vyberte typ média 
wiz_media_hint=Vyberte média, která nejlépe vyhovuje vašim ztrátě dat problém. V závislosti na vašem výběru, program optimalizovat proces obnovy.
wiz_volume=Vyberte Hlasitost pro skenování
wiz_volume_hint=Vyberte svazek, který chcete obnovit data. Pokud váš svazek není k dispozici, vybrat disk, který dělal obsahovat hlasitost.
wiz_volume_raid_hint=Chcete-li znovu rozbité RAID, vybrat RAID rekonstrukce.
wiz_volume_header=K dispozici disků a svazků:
wiz_volume_important=DŮLEŽITÉ: Ujistěte se, že je disk nebo připojené k systému, který poskytuje dostatek prostoru pro uložení obnovená data zjištěná během následujících scan!
wiz_volume_hintdisk=Vybrali jste si disk - zvolte disk, pouze pokud svazek není k dispozici.   
wiz_savevol=Vyberte Uložit hlasitosti 
wiz_savevol_hint=Vyberte svazek, který chcete uložit data.\ Poznámka: Ujistěte se, že není nutné obnovit data z vybraných uložit objem. 
wiz_savevol_availdisk=K dispozici disků a svazků:
wiz_savevol_path=Uložit cestu na objemu, kromě:
wiz_savevol_btnsavepath=Uživatelem definované ušetřit cestu 
wiz_scenario=Zvolte scénáře zotavení 
wiz_scenario_hint=Vyberte si oživení scénář, který nejlépe vyhovuje vašim ztrátě dat problém.
wiz_scenario_details=Vyberte souborové systémy pro vyhledávání:
wiz_scenario_enableraw=Povolit digitální podpis souboru skenování (RAW skenování)
wiz_scenario_enablequickscan=NTFS Rychlý test (Nemůžete najít všechny soubory)
wiz_check=Zkontrolujte své možnosti
wiz_check_hint=Zkontrolujte vybrané možnosti a spustit skenování. Vrať se, pokud chcete změnit jednu z možností. V závislosti na velikosti disku skenování proces může trvat několik hodin!
wiz_check_mediatype=Typ média:
wiz_check_volume=Objem:
wiz_check_disk=Disk:
wiz_check_scenario=Scénáře zotavení:
wiz_check_filesystems=Ásledující souborové systémy budou prohledávány:
wiz_check_savepath= Vaše soubory budou uloženy zde:
wiz_check_quickscan=Rychlýtest 
wiz_checkwipe_hint=Zkontrolujte vybrané možnosti a pokračovat. Vrať se, pokud chcete změnit jednu z možností.
wiz_scanning=Skenování disku...
wiz_scanning_hint=Vybraný disk je skenování - prosím čekejte! 
wiz_scanning_corrupt_note=Důležité: Všimněte si prosím, že se test mohl najít částečnou nebo poškozené soubory. Testovací soubory s aplikací skutečně zjistit, zda se data mohla být vrácena kompletně.
wiz_save=Uložit své soubory 
wiz_save_hint=Vyberte a uložte soubory, které chcete obnovit na jiný disk. Můžete zkontrolovat kvalitu obnovit soubory pomocí vestavěného v prohlížeči nebo otevření souborů s jejich aplikací.
wiz_backclear=To bude jasné stávající výsledků testů. Jste si jisti?
wiz_goback=Vrátit se 
wiz_continue=Pokračovat 
wiz_wipe=Otřete dat 
wiz_wipe_hint=Vyberte soubory a složky, vyberte Vymazat. POZOR: otřít soubory jsou nedobytné vymazány.
wiz_rescan=Jste již provedli kontrolu. Chcete se zbavit výsledků? Pokud zvolíte "Ano", bude nové skenování provést.
wiz_grplegend=Legenda
wiz_legend_lost=Ztracených nebo odstraněných složek 
wiz_legend_normal=Normální složky 

media_harddrive=Pevný disk 
media_harddrive_hint=Využívá data z interních pevných disků a dalších zařízení Mass Storage jako jsou externí pevné disky připojené, SSD disky atd.\n Poznámka: správně připojené zařízení je také viditelný v nástroji Správa disků v operačním systému.
media_memorycard=Paměťové zařízení 
media_memorycard_hint=Využívá data z flash disky nebo jiné vyměnitelné médium, jako je Flash paměť SD, CF, MMC, atd. připojen přes USB, Firewire, nebo jiného zařízení, čtečka digitálních médií.\n Poznámka: Zařízení musí vykazovat jako vyměnitelný disk nebo čtečka pro vyměnitelné médium musí být použit.
media_optical=Optická média 
media_optical_hint=Využívá data z optických médií, jako jsou CD, CDR/RW, DVD, DVDR/RW, atd.  
media_multimedia=Multimedia/ Mobile Device
media_multimedia_hint=Využívá data z multimediálních nebo mobilních zařízení, jako jsou digitální fotoaparát, MP3 přehrávač, chytrý telefon atd..\n Poznámka: Zařízení musí vykazovat jako vyměnitelný disk nebo čtečka pro vyměnitelné médium musí být použit.
media_raid=RAID systém 
media_raid_hint=Získává data z RAID systémů. Můžete také rekonstruovat rozbité RAID s tím.

vol_volumes=Objemy 
vol_type=Typ
vol_size=Velikost
vol_filesystem=Souborový systém 
vol_disk=Disk 
vol_lostvolume=Ztracené objem
vol_volume=Objem 

op_explore=Prozkoumejte hlasitosti 
op_explore_hint=Prozkoumejte platné objem Explorer jako rozhraní. Zvolte tuto možnost pro uložení dat z platného svazku. Žádné skenování se jedná.
op_deleted=Obnova smazaného souboru 
op_deleted_hint=Hledat omylem smazané soubory nebo ztracené soubory podle obsahu. Také zvolíte tuto možnost, pokud máte smazaných souborů z koše, nebo v případě, že oživení ve formátu nemůže najít soubory. V závislosti na možnostech všech nebo jen nepoužité bloky svazku mají být kontrolovány.
op_formatted=Formátovaný Media zotavení 
op_formatted_hint=Využívá data z formátu objemu. To může být také použit ke zpětnému získání ztracených souborů z non-formátována. Tato možnost vyžaduje více času na testování, ale má lepší šance na uzdravení. Skenuje každý blok objem ztracené struktury souborového systému.
op_volumes=Hledání ztracené svazky 
op_volumes_hint=Scan Disk pro ztracené či odstraněné svazky. Skenuje každý blok pro ztracené množství podpisů. To může také najít svazky, které nedokáží připojit.
op_wipe=Otřete dat 
op_wipe_hint=Bezpečně maže jednotlivé soubory nebo složky tak, aby nemohly být získány zpět už ne.
opt_caption=Možnosti 
opt_general=Generálníopt_recovery=Obnova 
opt_scanregion=Skenování kraj 
opt_wipeoptions=Možnosti otřete 
opt_badblockmanage=Bad bloku řízení
opt_deletedrecovery=Obnova smazaného souboru 
opt_textrecovery=Obnovení textu
opt_filetypes=Typy souborů 
opt_allocatedspace=Přidělené místo 
opt_filesystems=Souborové systémy
opt_logging=Přihlášení 
opt_expertmode=Expert Mode 
opt_scanoptions=Možností skenování 
opt_view=Možnosti zobrazení 
opt_tabSheetScanRegion=Skenování kraj 
opt_tabSheetScanRegion_lbltop=U velmi velkých disků, to může být užitečné omezit skenování na určitý rozsah disku. Tím se urychlí skenování a snížit počet nalezených souborů. Tato možnost platí pro všechny scénáře skenování.
opt_tabSheetScanRegion_lblstart=Začátek v:
opt_tabSheetScanRegion_lblstop=Stop na:
opt_tabSheetFileTypes=Typy souborů 
opt_tabSheetFileTypes_lbltop=Pro urychlení kontroly nebo omezit počet nalezených souborů, můžete zakázat určité typy souborů, pro všechny scénáře skenování zde.
opt_tabSheetFileTypes_lblfilter=Vyberte typy souborů filtr:
opt_tabSheetFileTypes_lbltypes=Povoleno typy souborů:
opt_tabSheetFileTypes_filetype=Typ souboru 
opt_tabSheetFileTypes_extension=Prodloužení
opt_filetypesfilter_all=Všechny soubory
opt_filetypesfilter_images=Obrazové soubory
opt_filetypesfilter_videos=Video soubory 
opt_filetypesfilter_audio=Zvukové soubory 
opt_filetypesfilter_apps=Souborů aplikace 
opt_filetypesfilter_office=Office dokumenty 
opt_filetypesfilter_text=Textové dokumenty 
opt_filetypesfilter_custom=Zvyk
opt_tabSheetFileSystems=Souborové systémy 
opt_tabSheetFileSystems_lbltop=Pro urychlení kontroly nebo omezit počet nalezených souborů, můžete vypnout některé souborové systémy pro všechny scénáře skenování zde.
opt_tabSheetFileSystems_fs=Souborové systémy
opt_tabSheetFileSystems_name=Jméno 
opt_tabSheetFileSystems_descr=Popis
opt_tabSheetLogging=Přihlášení 
opt_tabSheetLogging_lbltop=Zde si můžete vybrat úroveň výřečnosti pro logování zpráv a další nastavení záznamu:
opt_tabSheetLogging_lbllvl=Aktuální úroveň logování:
opt_tabSheetLogging_filename=Log souboru:
opt_tabSheetBadBlockMgr=Bad bloku manažer 
opt_tabSheetBadBlockMgr_lbltop=Můžete zobrazit a upravit špatný blok se pohybuje v tabulce níže. Tyto bloku se pohybuje, bude automaticky přeskočen během kontroly disku.
opt_tabSheetBadBlockMgr_range=Blockrange:
opt_tabSheetBadBlockMgr_from=Z
opt_tabSheetBadBlockMgr_to=Na 
opt_tabSheetBadBlockMgr_editfrom=Od:
opt_tabSheetBadBlockMgr_editto=Na:
opt_tabSheetBadBlockMgr_btnaddentry=Přidat položku

opt_tabSheetBadBlockMgr_btndelentry=Odstranit záznam
opt_tabSheetBadBlockMgr_btnApply=Platit 
opt_tabSheetBadBlockMgr_cbautoadd=Automaticky přidat vadných 
opt_tabSheetBadBlockMgr_cbautoskip=Automaticky vynechat seznam položek 
opt_tabSheetBadBlockMgr_btnsaveList=Uložit seznam 
opt_tabSheetBadBlockMgr_btnloadList=Zatížení seznam 
opt_tabSheetBadBlockMgr_btnClearList=Vymazat seznam
opt_tabSheetBadBlockMgr_cbfastbadblkskipping=Rychlý špatný blok přeskakování 
opt_tabSheetViewOpt=Možnosti prohlížeče 
opt_tabSheetViewOpt_lbltop=Různé možnosti zobrazení jsou zobrazeny v této záložce. Expertní režim umožňuje zkušeným uživatelům používat pokročilé využití funkce. Budete mít více možností v menu a možnost manipulovat se obnovené soubory a jejich parametry.

opt_tabSheetViewOpt_cbexpert=Ovolit Expert Mode 
opt_tabSheetViewOpt_cbautorem=Automaticky odstranit prázdné složky
opt_tabSheetScanOptions=Možností skenování 
opt_tabSheetScanOptions_grpraw=RAW Analyser
opt_tabSheetScanOptions_lbltop=Změna volby skenování zlepšit čas kontroly a výsledcích kontroly.
opt_tabSheetScanOptions_skipusedallocblks=Přeskočit jím užívaných blocích souborového systému na vybrané, platné objem:
opt_tabSheetScanOptions_cbMaxLostFileSize=Limit pro velikost souboru RAW souboru analyzátoru:
opt_tabSheetScanOptions_lblRawMin=Bytes minimum / %s
opt_tabSheetScanOptions_lblRawMax=Bytes maximum / %s
opt_tabSheetScanOptions_cbAutoConcatVideos=Pokuste se spojit rozbité video streamů
opt_tabSheetScanOptions_cbautorename=Automatické přejmenování souborů na stejný souborů na Uložit.
opt_tabSheetScanOptions_autoOffset=Automatická detekce blok offset 
opt_tabSheetScanOptions_detectdeleted=Detekce odstraněných souborů ve formátu skenování
opt_tabSheetScanOptions_ignoreallerr=Ignorovat všechny chyby při skenování.
opt_tabSheetScanOptions_onlyrootItems=Sbírejte pouze root položky Formátovaný Scan (pro skenování > 300GB)
opt_tabSheetScanOptions_popupsize_userdef=Uživatelem definované 
opt_tabSheetWipeOptions=Možnosti otřete 
opt_tabSheetWipeOptions_lbltop=Zde si můžete vybrat mezi různými možnostmi vymazat:
opt_tabSheetWipeOptions_lblwipemethod=Otřete metody:
opt_tabSheetWipeOptions_cbcreatereport=Vytvořte vymazání zprávy 
opt_okbtn=OK
opt_cancelbtn=Zrušit
opt_helpbtn=Pomoc 

about_copyright=LC Technology International, Inc.\nVšechna práva vyhrazena.
about_builddate=Datum výroby:
about_law=Tento počítačový program je chráněn autorským zákonem a mezinárodními smlouvami. Nepovolené kopírování nebo rozšiřování této nebo jakékoli jeho části může mít za následek závažné občanskoprávní a trestní postihy a budou stíháni v maximálním možném zákonem.

raid_caption=Rekonstruovat RAID 
raid_about=The RAID Rekonstrukce vám pomůže obnovit rozbité RAID systém de-striping RAID disk komponenty. Pokud nechcete znát RAID parametry, stačí zadat parametry označených níže a snímání na pravé straně může pokusit se najít chybějící parametry.
raid_selectnumber=Vyberte počet prvků v RAID řada:
raid_disks=# disky:
raid_selectcomponents=Vyberte komponenty, které své RAID řada:
raid_choosedisks=Vyberte disky 
raid_startsectors=Začátek odvětví:
raid_stripesize=Stripe size (odvětví)
raid_parityrotation=Parita rotace:
raid_findparams=Finding RAID parametry (volitelně)
raid_findabout=Pokud nechcete znát RAID parameters, který prohledá váš komponenty a pokuste se zjistit chybějící RAID parametry.
raid_startscan=Spustit skenování
raid_cancelscan=Storno skenování
raid_scanning=Skenování komponenty ... Prosím, vyčkejte!
raid_choosecombination=Vyberte si jednu z kombinací nastavení RAID parametrů. Jsou seřazeny podle pravděpodobnosti - čím vyšší skóre, tím je větší pravděpodobnost spojení.
raid_probedcombinations= Sondoval kombinace:
raid_startsector=Začátek sektoru
raid_stripesize2=Stripe velikosti
raid_parityrotation2=Parita rotace 
raid_score=Skóre
raid_error_sameblocksize=Disk komponenty musí mít stejnou velikost bloku!
raid_okinfo=Po kliknutí na OK, nová RAID disk je přidán, který lze použít k prohlížení rekonstrukci RAID disk, vytvořit soubor obrazu, nebo provést obnovu na to.
raid_options=Možnosti 
raid_order=Pořadí
raid_bestresults=Pro dosažení nejlepších výsledků používejte pouze hodnoty, které jsou pravděpodobné.
raid_paramsprobe=Parametry, které sonda:
raid_startsectors=Začátek odvětví 
raid_stripesizes=Stripe velikosti (odvětví)
raid_parityrotations=Parita rotace 
raid_diskorder=Disk, aby
raid_diskorder1=Disk pořadí:

other_erroropeningdisk=Disk nebo svazek nelze otevřít. Ujistěte se, že disk je správně připojen k počítači, a pokud je požádán, zadejte správné heslo uživatele root pro přístup k disku.
other_chooseimagefile=Vyberte destinaton a název image souboru
other_chooseRestoreImagefile=Vyberte si zdrojový soubor obrazu 
other_creatingimagefile=Vytváření image souboru
other_savingfiles=Ukládání souborů 
other_diskerrors=Disk chyby:%d
other_searchkeyword=Pro hledané klíčové slovo
other_wipeconfirmation=UPOZORNĚNÍ: vybrané soubory a složky budou nenávratně smazány. Přejete si pokračovat?
other_wipingfiles=Stírání soubory 
other_searchingitems=Vyhledávání položek 
other_choosedestfolder=Vyberte cílovou složku
other_appalreadyrunning=Aplikace je již spuštěna!
other_operationerror=Operace se nezdařila. errorCode =%d.
other_operationsuccess=Operace byla úspěšná.
other_freemem=Volná paměť:%s
other_freeswap=Zdarma vyměnit paměť:%s
other_x_of_y=%s of %s
other_table=Tabulka
other_thumbs=Náhledy 
other_enableautoenlarge=Povolit automatické zvětšení 
other_searchkeyword=Pro hledané klíčové slovo 
other_cannotsavetovolume=Není možné ukládat soubory do naskenované objemu. Prosím, vyberte jiný svazek.
other_featurenotavailable=Tato funkce není k dispozici v tomto výrobku variantu.
other_asksuretoclose=Tato aplikace bude uzavřena - Jste si jistý?
other_errorduringscan=Došlo k závažné chybě při poslední operaci. Viz podrobnosti v souboru protokolu.
other_fileexists=Soubor již existuje 
other_confirmoverwrite=Soubor %s již existuje. Chcete ho přepsat?
other_question=Otázka 
other_confirmRestoreImage=Restore přepíše všechna data na %s.\n Ujistěte se, že příslušná data byla odstraněna již dostal se z tohoto svazku.\n Přejete si pokračovat?
other_restoreimagefile=Obnovit image souboru 
other_restorewarning=To přepíše celý disk / svazek %s (%s). Jste si jisti?
other_confirmrefreshdisklist=Osvěžující seznamu disků odstraní obnovené svazků. Přejete si pokračovat?
other_saveThread_finishedmsg=Ukládání dokončení procesu. naprosto %d soubor (y) je / bylo uloženo.
other_savefolderreportThread_finishedmsg=Soubor zpráva byla vytvořena.
other_wipeThread_finishedmsg=Stírání dokončení procesu. naprosto %d soubor (y) je / byl vymazán.
other_wipediskThread_finishedmsg=Disk vymazání dokončení procesu.
other_wipereportThread_finishedmsg=Vymazání zpráva byla vytvořena.
other_scanDeletedFiles_finishedmsg=Smazané soubory skenování dokončeno.
other_scanLostFiles_finishedmsg=Soubory ve formátu skenování dokončeno.
other_scanLostVolumes_finishedmsg=Skenování ztracených svazků dokončení procesu.
other_CreateImageThread_finishedmsg_success=Obrázek byl úspěšně vytvořen.
other_CreateImageThread_finishedmsg_error=Vytváření image skončil s chybami. Viz log souboru pro další informace.
other_RestoreImageThread_finishedmsg_success=Obrázek byl úspěšně obnoven.
other_RestoreImageThread_finishedmsg_error=Restore selhala. Viz log souboru pro další informace.
other_diskfull=Aktuální položka vyžaduje %d MB.\n je zde %d MB volného místa na svazku %s.\n Přejete si uložit zbývající soubory na jiném svazku?
other_badblocklist=Bad bloku Seznam %s
other_savebadblocklist=Uložit špatný blok seznam ...
other_openbadblocklist=Otevřete špatný blok seznam ...
other_noadmin=Nejste pracovat jako správce na tomto počítači. Tento program nebude pracovat správně. Prosím, přihlaste se jako správce a znovu tuto aplikaci, nebo požádejte správce!
other_confirmopenfile=Otevření tohoto souboru bude zapisovat do %s.\n To může zničit nevybraných Data na tomto svazku.\n Přejete si pokračovat?
other_needminimumspace=Minimální %s volného místa, je zapotřebí %s.\nv současné době %s volného místa je k dispozici.\n Prosím, vyberte jiný svazek.
other_wipingdisk=Stírání disk 
other_wipediskwarning=Tím dojde k vymazání celého disku / svazku %s (%s).\n Všechna stávající data na něm bude možné získat přepsán.\n Jste si jisti?
other_addingtoreport=Přidávání položek do zprávy 

search_itemsfound=Nalezených položek:%d
search_itemmatch=Odpovídající položky:%s 

remote_descr=VNC vzdálené obnovení umožňuje podporovat partnerské na dálkové ovládání této aplikace z jiného počítače. Oba uživatelé mohou sdílet stejnou obrazovku. Vy a podporu partnera, musí být připojen přes LAN nebo WAN.
remote_steps=Kroky:\n\n1.) Vaše podpora partner musí začít svůj prohlížeč s určitým IP adresu a číslo portu.\n\n2.) Zadejte prosím IP adresa a číslo portu podporu partnerem v oblasti níže.\n\n3.) Poté stiskněte tlačítko "Připojit" tlačítko. 
remote_timeout=Pokud se připojení nezdaří, měli byste podporovat partnerské přidat port-forwarding jeho router a firewall na otevřít jeho číslo portu uvedeno v poli adresy níže.
remote_ipadr=Zadejte vzdálené adresy pro připojení k (IP Adresa: Port):
remote_vncnotfound=Dálkový VNC Viewer nebylo možné nalézt na %s.
remote_connectwait=Připojení ke vzdálenému počítači, čekejte prosím ...
remote_disconnectwait=Odpojení od vzdáleného počítače, čekejte prosím ...
remote_btnconnect=Připojit
remote_btndisconnect=Odpojit
remote_btnclose=Zavřít
remote_connect=Připojit
remote_connecting=Připojení ...
remote_connected=Připojeno.
remote_disconnect=Odpojit
remote_disconnecting=Odpojení ...
remote_disconnected=Odpojeno.
remote_choosebetween=Vyberte si mezi:
remote_paneltextviewer=Chci ovládat některé stroje.
remote_paneltextserver=Tento stroj je dálkově ovládané.
remote_stepsnew=Kroky:
remote_port=Port:
remote_tellipandport=Řekněte svému partnerovi své IP a přístav na telefonu.
remote_yourwanip=Svůj IP:
remote_waitforconnection=Počkejte, až váš partner připojí k vám.
remote_troubleshooting=Řešení problémů
remote_troubleshootingViewer=Pokud váš vzdálený partnera nemůže navázat spojení, je nutné znovu prověřit přesměrování portů a nastavení brány firewall na číslo portu je uvedeno výše.
remote_troubleshootingServer=Pokud se připojení nezdaří, měli byste podporovat partnerské přidat port-forwarding jeho router a firewall na otevřít jeho číslo portu uvedeno v poli adresy výše.
remote_serverwait=Počkejte, až ke vzdálené partnera řekne si svůj IP a port. Poté zadejte je zde:
remote_serverip=IP:
remote_serverport=Port:
remote_pressconnect=Stiskněte tlačítko Connect.
remoteview_formcaption=Prohlížeč vzdálené obnovení
remoteview_clickstart=Prosím, klikněte na tlačítko Start pro spuštění VNC Prohlížeč.
remoteview_wanipinstruct=Pak doporučujeme dálkového partnera zadat WAN IP adresu a číslo portu ve své vzdálené obnovení dialogu. Pokud si nejste jisti, o své WAN IP adresu, klikněte na odkaz na webové stránky níže.
remoteview_noconnection=Pokud váš vzdálený partnera nemůže navázat spojení, je nutné znovu prověřit přesměrování portů a nastavení brány firewall na číslo portu je uvedeno výše.
remoteview_bottom=Pokud váš vzdálený partnera připojí, otevře se nové okno automaticky ukazovat jeho ploše.
remoteview_portnum=Číslo portu je:
remoteview_startviewer=Začátek Viewer
remoteview_stopviewer=Zastavit Viewer

demomsgstart=Vyhodnocení verze tohoto softwaru je omezeno na:
demomsgfiles=%d soubory
demomsgmaxfilesize=Maximální velikost souboru %d KByte
demomsgtotalamount=V celkové výši %d KByte pro každého uživatele.
demomsgend=Se uzdravíte %d soubory %d KByte s tímto softwarem.
demomsgendbuy=Je nutné zakoupit plnou verzi pro ukládání souborů a složek bez omezení Vyhodnocení verze.

logging_none=Žádný
logging_info=INFO
logging_debug=DEBUG
logging_debug2=DEBUG2
logging_warning=VAROVÁNÍ
logging_error=CHYBA

core_Category_image=Obrázky
core_Category_application=Aplikace
core_Category_audio=Audio
core_Category_archive=Archiv
core_Category_document=Dokumenty
core_Category_video=Videa
core_Category_text=Text
core_Category_other=Další
core_Root=Kořen
core_Deleted=Odstraněné
core_Lost=Ztracený
core_OrphanedFolders=Osiřelé složky
core_SearchResults=Výsledky hledání
core_ContentOfFolder=Obsah složky: %s
core_Name=Jméno
core_Size=Velikost
core_Type=Typ
core_DateModified=Datum změny
core_ID=ID
core_Folder=Složka
core_File=Soubor
core_NotAvailable=N/A
core_analyserScanBegin=Spuštění analyzátory
core_analyserScanEnd=Zastavení analyzátory - čekejte prosím ...
core_scanning=Počkejte prosím, skenování disku ...
core_done=Provedeno
core_countingfiles=Počítání soubory ...
core_creatingreport=Vytváření zprávy ...
core_reportcancel=Tato zpráva není úplná / bylo zrušeno při vytváření.
core_blockOffsetDetection= Detecting block offset
core_FileSystem=Souborový systém
core_checked=X
core_scanType_scanBrowse=Procházet soubory
core_scanType_scanDeletedFiles=Hledat smazané soubory
core_scanType_scanLostFiles=Hledání ztracených souborů
core_scanType_scanLostVolumes=Hledání ztracené svazky
core_scanType_Wipe=Otřete soubory
core_skip=Přeskočit

tscanSettingName_No=Ne
tscanSettingName_Yes=Ano
tscanSettingName_Auto=Automatický

report_choosename=Zvolte si název souboru pro soubor zprávy
report_saving=Ukládání zprávy ...
report_on_date=Seznam souborů zprávu %s 

viewer_formcaption=Viewer
viewer_radiogroupcaption=Zobrazit jako
viewer_radiobuttontext=Text
viewer_radiobuttonBinary=Binární
viewer_radiobuttonHex=HEX
viewer_radiobuttonUnicode=Unicode

wipe_reportheader=Odstranit potvrzení certifikátu

core_wipe_deletiondate=Vymazání Datum:%s
core_wipe_volume=Odstraněny na svazku:'%s'
core_wipe_method=Způsob odstranění:%s
core_wipe_methodzerowrite=Napište nuly
core_wipe_methodrandomNumbers=Náhodných čísel
core_wipe_methodtogglebits=Přepínání bitů
core_wipe_totalbytesprocessed=Celkové zpracování bytů:%d
core_wipe_totalitemsprocessed=Celkem zpracovaných položek:%d
core_wipe_fileentry='%s' (souboru), velikost v bajtech:%d, Data změny: %s, stav:%s
core_wipe_folderentry='%s' (složku), data změny: %s, s